services:
  database:
    image: postgres:latest
    container_name: shareit-database
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d shareit" ]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      target: server
    image: shareit-server:latest
    container_name: shareit-server
    expose:
      - "9090"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/shareit
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Moscow
  gateway:
    build:
      context: .
      target: gateway
    image: shareit-gateway:latest
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=Europe/Moscow